version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-app
    container_name: customer-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: customer-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:5.7
    container_name: customer-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
